# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Sample configuration for the landing page theme
# Replace these values with your own!
title: Halil Can Kaskavalci
description: >- # this means to ignore newlines until "baseurl:"
  Engineering Leader @ Booking.com

  Always learning, occasionally building.
name: Halil
tagline: Leader | Father | Engineer | Learner
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kaskavalci.com" # the base hostname & protocol for your site, e.g. http://example.com

# Links
email: contact@halil.kaskavalci.com
github_username: kaskavalci
linkedin_username: kaskavalci
# twitter_username: your-twitter-username
# resume_url: "/assets/resume.pdf"
blog_url: "https://blog.kaskavalci.com"

# Portfolio Projects
# Add your projects here. Each project should have:
# - title: The name of your project
# - description: A brief description of what the project does
# - demo_url: (optional) Link to live demo
# - github_url: (optional) Link to GitHub repository
portfolio:
  - title: "Montessori Shopping List"
    image_url: "https://montessori-shopping-list.kaskavalci.com/gnome-logo.jpg"
    description: "AI assisted shopping list for kids"
    demo_url: "https://montessori-shopping-list.kaskavalci.com"
    # github_url: "https://github.com/username/project-one"

  - title: "Jekyll Landing Page"
    description: "Basically this page"
    image_url: "/assets/simple-landing-page.png"
    demo_url: "https://kaskavalci.github.io/simple-landing-page/"
    github_url: "https://github.com/kaskavalci/simple-landing-page"

  # - title: "Project Three"
  #   description: "A backend service with RESTful API and microservices architecture."
  #   github_url: "https://github.com/username/project-three"

# Build settings
plugins:
  - jekyll-feed
